### ISSUE TITLE
Output Date Format

### ISSUE THREAD

**Issue by athom09** [dracos/django-date-extensions#5]
There does not seem to be a way to keep / specify the format you want the widget to output.
For example if I put "01/05" and save the object  and then retrieve it again it displays as "5th January".  I would like a way to say display as "01/05".

**Comment by dracos** [comment]
On the original issue, this is now fixed by #8 which allows you to override the output/input formats in your project settings. I'm afraid I didn't see that the reply was a different issue previously - I do include the south introspection command needed in `fields.py` but perhaps it is not being seen for some reason, if you try importing the class, perhaps that might help. Hopefully you can switch to Django 1.7 and migrations, it should be okay there; if not, please open a new issue.
