### ISSUE TITLE
ApproximateDateField Filtering by None value never matches

### ISSUE THREAD

**Issue by jplehmann** [dracos/django-date-extensions#7]
Given an object with an ApproximateDateField (ADF), query for other objects with the same ADF.  If the ADF field is None, other equivalent objects will not match. 

```
e1 = MyEntity.objects.filter(pk=1)
assert e1.adf == None
e2 = MyEntity.objects.filter(pk=2)
assert e2.adf == None
assert MyEntity.objects.filter(adf=e1.adf).count() == 0
```

I would expect the query to return at least e2.  I have to add special logic to filter instead on adf being equal to "" if adf is None.

I realize that in SQL that NULL <> NULL, but I tried doing this with other fields that support None and it worked.

My workaround:

    q = q.filter(dob=self.dob) if self.dob != None else q.filter(dob='')

**Comment by dracos** [comment]
I think it assumes you use `""` rather than None. The Django docs do say "Avoid using null on string-based fields such as CharField and TextField" and ApproximateDateField is a CharField subclass, so that's probably what I was thinking.

**Comment by jplehmann** [comment]
So you're saying it's preferred to represent an unknown value with "" instead of None, but how would I create an ADF with ""?  It appears to require a year, unlike string, where I can assign "" for empty.

Not to mention, it's surprising to me at least that this would behave like a String.

thanks for your quick response!

**Comment by dracos** [comment]
If you create your ApproximateDateField with blank=True, then you can create empty values with an empty string, yes:
```
>>> A.TestModel(dob='')
<TestModel: None>
```
It's a string because that's how it stores it in the database (whilst MySQL can support dates like 2000-00-00, PostgreSQL and others do not); it tries to hide this but it quite possibly could deal with emptiness better.

**Comment by jplehmann** [comment]
Thanks Matthew.  I tried setting the field to blank rather than None, but
that didn't seem to help me much.

In [56]: s = MyObject.objects.filter(id=23468).get()

In [57]: MyObject.objects.filter(id=23468).filter(dob="")

Out[57]: [< MyObject: MyObject object>]

In [58]: MyObject.objects.filter(id=23468).filter(dob=s.dob)

Out[58]: []


So I have to do something like this:

In [65]: MyObject.objects.filter(id=23468).filter(dob=s.dob if s.dob else
"")

Out[65]: [< MyObject: MyObject object>]


I think the weird part is that s.dob gets rendered as None, therefore you
can't feed it directly back into the filter.

**Comment by dracos** [comment]
That isn't great, isn't it. The culprit is a combination of the fact that `to_python` returns None if the input is "" or None, whilst `get_db_prep_value` isn't called on a None input (it's already been turned into an `__isnull=True` query parameter. It looks like if we return "" in to_python, that would fix the issue, I'm not sure if that affects anything, but I don't see why it would.

(Aside, you could do `s.dob or ""` rather than your ternary.)

**Comment by dracos** [comment]
Hi, Apologies for the severe delay in dealing with this, but I've just released version 2 that hopefully has more consistent and obvious behaviour when querying for dates - an empty string will be returned for an empty date, and it should match against other objects with empty dates.
